# Generated by Django 4.2 on 2024-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
